version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cachetools
    versions:
    - 4.2.1
  - dependency-name: watchdog
    versions:
    - 2.0.2
